### ISSUE TITLE
crash in PayPal plugin

### ISSUE THREAD

**Issue by juszczec** [paypal/PayPal-Cordova-Plugin#63]
hello

research shows this happened before as reported in:

https://github.com/paypal/PayPal-Cordova-Plugin/issues/52

i have upgraded to version 3.1.4 per the comments in the issue report above but the problem still happens.

the error:

2015-03-21 08:30:42.816 MyCordovaShop[830:4707] bool _WebTryThreadLock(bool), 0x14df2870: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
1   0x38e24513 WebThreadLock
2   0x3384a813 <redacted>
3   0x3359601d <redacted>
4   0x334a14b7 <redacted>
5   0x3349a4b7 <redacted>
6   0x335ef2a7 <redacted>
7   0x3355b5cb <redacted>
8   0x6a6f9 __51-[PayPalMobileCordovaPlugin renderSinglePaymentUI:]_block_invoke
9   0x3b8ef833 <redacted>
10  0x3b902921 <redacted>
11  0x3b902b21 <redacted>
12  0x3ba31bd3 _pthread_wqthread
13  0x3ba31a98 start_wqthread

so far, i've gotten this to happen on:

iphone 4 running ios 7.1.2
iphone 6 emulator

i'm running:

osx 10.9.5
cordova 4.3.0
jquery 1.11.1
jquery mobile 1.4.5
jquery.ui.map
JQMDateBox
iscroll
iscrollview

here are the cordova plugins i am using:

com.paypal.cordova.mobilesdk 3.1.4 "PayPalMobile"
org.apache.cordova.console 0.2.11 "Console"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.statusbar 0.1.10 "StatusBar"

and my Xcode is:

6.2 (6C131e)

i am very anxious to get the pay pal plugin working in my project and am happy to help in any way possible.

how shall we proceed?

**Comment by romk1n** [comment]
@juszczec that's weird all the UI presentation should happen on the main thread. Try setting a few breakpoints and check when it happens  [here](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/src/ios/PayPalMobileCordovaPlugin.m#L145) and [here](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/src/ios/PayPalMobileCordovaPlugin.m#L314) and [here](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/src/ios/PayPalMobileCordovaPlugin.m#L320)

**Comment by juszczec** [comment]
@romk1n something isn't right.  my source file doesn't match the one shown in your links.

my lines:

145:    }];

314:- (void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController didCompletePayment:

320:  }];

i'm not sure what's wrong.  i updated to 3.1.4 last night.  the comment at the top of the file shown in your link says "romk1n 26 days ago update version to 3.1.3 "

**Comment by romk1n** [comment]
@juszczec you need first to remove plugin and then install try it like this

```bash
cordova plugin rm com.paypal.cordova.mobilesdk
cordova plugin add com.paypal.cordova.mobilesdk
```

**Comment by juszczec** [comment]
i have done so and now i'm getting the errors below which is odd because 3.1.3 worked just fine.

Marks-MacBook-Pro:MyCordovaShop markj$ cordova build ios
Running command: /Users/markj/MyCordovaShop/platforms/ios/cordova/build 
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/markj/MyCordovaShop/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.2
    VALID_ARCHS = i386

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies
2015-03-21 15:57:46.173 xcodebuild[977:5403]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/markj/Library/Developer/Xcode/DeveloperPortal%206.2.db).

=== BUILD TARGET MyCordovaShop OF PROJECT MyCordovaShop WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/MyCordovaShop.build/Debug-iphonesimulator/MyCordovaShop.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/markj/MyCordovaShop/platforms/ios
    /bin/sh -c /Users/markj/MyCordovaShop/platforms/ios/build/MyCordovaShop.build/Debug-iphonesimulator/MyCordovaShop.build/Script-304B58A110DAC018002A0835.sh

real	0m0.184s
user	0m0.068s
sys	0m0.100s

ProcessInfoPlistFile build/emulator/MyCordovaShop.app/Info.plist MyCordovaShop/MyCordovaShop-Info.plist
    cd /Users/markj/MyCordovaShop/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    builtin-infoPlistUtility /Users/markj/MyCordovaShop/platforms/ios/MyCordovaShop/MyCordovaShop-Info.plist -genpkginfo /Users/markj/MyCordovaShop/platforms/ios/build/emulator/MyCordovaShop.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/markj/MyCordovaShop/platforms/ios/build/MyCordovaShop.build/Debug-iphonesimulator/MyCordovaShop.build/MainViewController-PartialInfo.plist -o /Users/markj/MyCordovaShop/platforms/ios/build/emulator/MyCordovaShop.app/Info.plist

Ld build/emulator/MyCordovaShop.app/MyCordovaShop normal i386
    cd /Users/markj/MyCordovaShop/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -L/Users/markj/MyCordovaShop/platforms/ios/build/emulator -L/Users/markj/MyCordovaShop/platforms/ios/MyCordovaShop/Plugins/com.paypal.cordova.mobilesdk -F/Users/markj/MyCordovaShop/platforms/ios/build/emulator -filelist /Users/markj/MyCordovaShop/platforms/ios/build/MyCordovaShop.build/Debug-iphonesimulator/MyCordovaShop.build/Objects-normal/i386/MyCordovaShop.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -force_load /Users/markj/MyCordovaShop/platforms/ios/build/emulator/libCordova.a -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=6.0 -framework AssetsLibrary /Users/markj/MyCordovaShop/platforms/ios/build/emulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -lc++ -Xlinker -dependency_info -Xlinker /Users/markj/MyCordovaShop/platforms/ios/build/MyCordovaShop.build/Debug-iphonesimulator/MyCordovaShop.build/Objects-normal/i386/MyCordovaShop_dependency_info.dat -o /Users/markj/MyCordovaShop/platforms/ios/build/emulator/MyCordovaShop.app/MyCordovaShop
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CLLocationManager", referenced from:
      objc-class-ref in CDVLocation.o
  "_kCLLocationAccuracyBest", referenced from:
      -[CDVLocation startLocation:] in CDVLocation.o
  "_kCLLocationAccuracyNearestTenMeters", referenced from:
      -[CDVLocation startLocation:] in CDVLocation.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/MyCordovaShop.app/MyCordovaShop normal i386
(1 failure)
ERROR building one of the platforms: Error: /Users/markj/MyCordovaShop/platforms/ios/cordova/build: Command failed with exit code 65
You may not have the required environment or OS to build this project
Error: /Users/markj/MyCordovaShop/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

**Comment by romk1n** [comment]
@juszczec those are linking errors. try also removing and re-adding platform `cordova platform remove ios` `cordova platform add ios`

**Comment by juszczec** [comment]
i apologize.  i had botched up the update from 3.1.3 to 3.1.4

everything is working now.

thank you very much and sorry for wasting your time

**Comment by romk1n** [comment]
@juszczec can you still reproduce original issue ?

**Comment by juszczec** [comment]
i cannot reproduce the issue since upgrading to 3.1.4  

when i reported the issue, i thought i had upgraded to 3.1.4 

i was mistaken.  i made a mistake upgrading to 3.1.4, that's why my source didn't match your link.

once i upgraded properly, the problem went away.

**Comment by romk1n** [comment]
@juszczec great!

**Comment by juszczec** [comment]
sorry about wasting your time and thank you for all the help

**Comment by matthewborgcarr** [comment]
I have a mobile app with com.paypal.cordova.mobilesdk v3.5.0

I am getting the following error when creating payment in iOS.

Please also note that the app crashes and closes immediately when not in debug mode.

`
2018-09-02 20:48:29.853486+0200 MyHurryApp[631:122102] -[NSNull length]: unrecognized selector sent to instance 0x1b69ef878
2018-09-02 20:48:29.856680+0200 MyHurryApp[631:122102] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1b69ef878'
*** First throw call stack:
(0x1843bad8c 0x1835745ec 0x1843c8098 0x1843c05c8 0x1842a641c 0x102ad75e8 0x1028c1c20 0x1033211dc 0x10332119c 0x103325d2c 0x184363070 0x184360bc8 0x184280da8 0x186266020 0x18e2a0758 0x1028beb90 0x183d11fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
`

The line causing this crash seems to be:  [PayPalMobile `preconnectWithEnvironment:environmentToUse];`

```
- (void)prepareToRender:(CDVInvokedUrlCommand *)command { [self.commandDelegate runInBackground:^{ CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK]; NSString *environment = [command.arguments objectAtIndex:0];

NSString *environmentToUse = [self parseEnvironment:environment];
if (environmentToUse) {
  // save configuration
  PayPalConfiguration *configuration = [self getPayPalConfigurationFromDictionary:[command.arguments objectAtIndex:1]];
  self.configuration = configuration;
  // do preconnect
  dispatch_async(dispatch_get_main_queue(), ^{
    [PayPalMobile preconnectWithEnvironment:environmentToUse];
  });
} else {
  pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"The provided environment is not supported"];
}

[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}]; } 
```

In other forums I've seen suggestions that you should convert the payment amount to string, which I did however the issue is still there.

any other suggestions?
